import fileinput
import subprocess
import sys

path = sys.argv[1]

cmdHash = "git rev-parse --short HEAD"
print str(dir)
getHash =  subprocess.Popen(cmdHash, shell=True, stdout=subprocess.PIPE).stdout
githash =  getHash.read()

finalstring = "#define BUILD_GIT_HASH 0x" + githash

f = open(str(sys.argv[1]), "w")
f.write("// autogenerated file from build_def_GitHashChanger.py, do not modify\n\n#ifndef BUILD_HASH_H\n\n#define BUILD_HASH_H\n\n")
f.write(finalstring)
f.write("\n\n#endif // BUILD_HASH_H")
f.close()


sys.exit(0)